repos:
-   repo: https://github.com/python/black
    rev: 19.3b0
    hooks:
    -   id: black
        args: [--safe, --quiet]
        language_version: python3
-   repo: https://github.com/asottile/blacken-docs
    rev: v0.5.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==19.3b0]
        language_version: python3
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
    -   id: flake8
        additional_dependencies: [
                flake8-import-order,
                flake8-bandit,
                flake8-blind-except,
                flake8-bugbear,
                flake8-builtins,
                flake8-docstrings,
                flake8-logging-format,
                pep8-naming,
                pygments,
          ]
        language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: check-yaml
    -   id: check-json
        language_version: python3
